name: CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/ci.yml'
      - '!*.md'
  repository_dispatch:
    types: ci-completed
  workflow_dispatch:

jobs:
  ci:
    name: CI - Compile by latexmk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install the packages
        run: |
          sudo apt-get update
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install -y texlive-full python3 ttf-mscorefonts-installer
          mkdir simfonts && wget -qO- https://github.com/yusanshi/hnuthesis/files/6371620/SimFonts.tar.gz | tar xz -C simfonts
          mkdir -p ~/.local/share/fonts && mv simfonts ~/.local/share/fonts
          fc-cache -f
      - name: Compile the TeX files
        run: |
          set -e
          latexmk -xelatex -shell-escape main.tex
